# global configuration
num_workers: 4                # Number of workers for DataLoader
seed: 42                      # Random seed for reproducibility
device: cuda                  # Device to use (cpu, cuda, cuda:0, etc.)
verbose: false                # Whether to display progress bars
save_interval: 500            # Interval of epochs to save checkpoints
log_interval: 50              # Interval to log training statistics
ckpt_dir: ./ckpts

# Dataset configuration
dataset:
  name: llff                    # Dataset class name
  base_dir: ./data/nerf_llff_data # Path to the dataset
  object: room                  # Object to render
  image_folder: images          # Folder with images
  factor: 8                     # Resizing factor for images
  image_preload: true           # Whether to preload all images into memory
  n_sample_rays: 1024           # Number of rays to sample from each image (None means use all rays)
  boundary_factor: 0.75         # Scaling factor for the boundary (optional)
  test_spiral: false            # Use spiral path for testing
  n_sample_rays: 1024           # Number of rays to sample from each image (None means use all rays)


# Model configuration
model:
  name: 'basic_nerf'            # Model class name
  coarse_model_params:
    xyz_dim: 3                    # Number of input dimensions for the network
    xyz_embedding_dim: 10         # Dimension of the spatial embedding
    direction_dim: 3              # Number of input dimensions for viewing directions
    direction_embedding_dim: 4    # Dimension of the view direction embedding
    n_layers: 8                   # Number of layers in the fine network
    hidden_dim: 256               # Number of hidden units in each layer
    skip_concat_connection: [4]   # Layers at which to concatenate the input features
    skip_connection: []           # Layers at which to add skip connections
  fine_model_params:
    xyz_dim: 3                    # Number of input dimensions for the network
    xyz_embedding_dim: 10         # Dimension of the spatial embedding
    direction_dim: 3              # Number of input dimensions for viewing directions
    direction_embedding_dim: 4    # Dimension of the view direction embedding
    n_layers: 8                   # Number of layers in the fine network
    hidden_dim: 256               # Number of hidden units in each layer
    skip_concat_connection: [4]   # Layers at which to concatenate the input features
    skip_connection: []           # Layers at which to add skip connections

# Optimizer configuration
optimizer:
  name: adam                    # Type of optimizer (adam, sgd, etc.)
  optimizer_params:
    lr: 0.0005                  # Learning rate
    betas: [0.9, 0.999]         # Adam's beta parameters

# Scheduler configuration
scheduler:
  name: step                    # Scheduler type (step, cosine, etc.)
  scheduler_params:
    step_size: 400               # Number of steps to reduce learning rate
    gamma: 0.95                   # Multiplicative factor of learning rate decay

# Loss function configuration
loss:
  name: l2                     # Loss function to use (l2 for MSELoss)

# Training configuration
train:
  batch_size: 2                 # Batch size
  num_epochs: 20000             # Number of epochs to train
  verbose: true                 # Whether to display progress bars
  output_dir: ./outputs         # Directory to save outputs/checkpoints
  n_coarse_samples: 64          # Number of stratified samples for the coarse network
  n_fine_samples: 128           # Number of samples for the fine network
  white_bkgd: true              # Use white background for training
  perturb: 1.0                  # Standard deviation of noise added to raw predictions
  raw_noise_std: 1.0

# Testing configuration
test:
  test_only: false              # Only run testing without training
  test_spiral: false            # If set to true, test with spiral path instead of regular

# Ray sampling configuration
# ray_sampling:
#   n_samples: 64                 # Number of stratified samples for the coarse network
#   n_samples_importance: 64       # Number of samples for the fine network
#   perturb: true                 # Whether to add noise to stratified samples
#   raw_noise_std: 0.1            # Standard deviation of noise added to raw predictions

# # Logging and visualization
# logging:
#   tensorboard: true             # Enable TensorBoard logging
#   log_dir: ./logs               # TensorBoard log directory
#   log_train_loss: true          # Log the training loss
